//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AHU()
        {
            this.AHUTransactions = new HashSet<AHUTransaction>();
        }
    
        public long ID { get; set; }
        public string Project { get; set; }
        public string UnitTag { get; set; }
        public string PartNo { get; set; }
        public string Model { get; set; }
        public string PowerSupply { get; set; }
        public string FanType { get; set; }
        public string MotorPole { get; set; }
        public string FanMotor { get; set; }
        public string FanRPM { get; set; }
        public string FanPulley { get; set; }
        public string MotorPulley { get; set; }
        public string Belt { get; set; }
        public Nullable<int> Section { get; set; }
        public string CoolingCoil1 { get; set; }
        public string CoolingCoil2 { get; set; }
        public string HeatingCoil1 { get; set; }
        public string HeatingCoil2 { get; set; }
        public string Heater { get; set; }
        public string SalesOrder { get; set; }
        public decimal Item { get; set; }
        public string SerialNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> ShipStatus { get; set; }
        public Nullable<int> SectionReceived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AHUTransaction> AHUTransactions { get; set; }
    }
}
