//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHUTransaction
    {
        public long ID { get; set; }
        public long CountryID { get; set; }
        public decimal Quantity { get; set; }
        public long AHUID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AHU AHU { get; set; }
        public virtual Country Country { get; set; }
    }
}
