//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCU()
        {
            this.FCUTransactions = new HashSet<FCUTransaction>();
        }
    
        public long ID { get; set; }
        public string Project { get; set; }
        public string UnitTag { get; set; }
        public string PartNo { get; set; }
        public string Model { get; set; }
        public string PowerSupply { get; set; }
        public string FanMotor1 { get; set; }
        public string FanMotor2 { get; set; }
        public decimal Qty { get; set; }
        public string CoolingCoil { get; set; }
        public string HeatingCoil { get; set; }
        public string Heater { get; set; }
        public string SalesOrder { get; set; }
        public decimal Item { get; set; }
        public string SerialNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> ShipStatus { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCUTransaction> FCUTransactions { get; set; }
    }
}
