//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsReceive()
        {
            this.EunKGs = new HashSet<EunKG>();
            this.GITransactions = new HashSet<GITransaction>();
            this.GRTransactions = new HashSet<GRTransaction>();
        }
    
        public long ID { get; set; }
        public string PurchaseOrder { get; set; }
        public string Vendor { get; set; }
        public string DeliveryNote { get; set; }
        public string BillOfLading { get; set; }
        public string HeaderText { get; set; }
        public string Material { get; set; }
        public string MaterialShortText { get; set; }
        public Nullable<bool> Ok { get; set; }
        public decimal Quantity { get; set; }
        public string Eun { get; set; }
        public string MvmtType { get; set; }
        public string StorageLoc { get; set; }
        public int Plant { get; set; }
        public string StorageBin { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EunKG> EunKGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GITransaction> GITransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRTransaction> GRTransactions { get; set; }
    }
}
