--Create Roles table

CREATE TABLE Role(
	ID BIGINT PRIMARY KEY,
	Name NVARCHAR(200) NOT NULL,
	Code NVARCHAR(100) NOT NULL,
	Description NVARCHAR(100) NOT NULL,
	Enabled NVARCHAR(1) NOT NULL Default 'Y',
	CreatedOn DATETIME NOT NULL,
	CreatedBy NVARCHAR(20) NOT NULL,
	ModifiedOn DATETIME NOT NULL,
	ModifiedBy NVARCHAR(20) NOT NULL)