--Create Users table

CREATE TABLE Users (
	ID BIGINT PRIMARY KEY,
	Username NVARCHAR(20) NOT NULL,
	Password NVARCHAR(32) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	RoleID BIGINT NOT NULL,
	Enabled NVARCHAR(1) NOT NULL Default 'Y',
	CreatedOn DATETIME NOT NULL,
	CreatedBy NVARCHAR(20) NOT NULL,
	ModifiedOn DATETIME NOT NULL,
	ModifiedBy NVARCHAR(20) NOT NULL)