--Create Container table

CREATE TABLE Container (
	ID BIGINT PRIMARY KEY,
	PartNumber NVARCHAR(200) NOT NULL,
	Description NVARCHAR(135) NOT NULL,
	MachineUsage NVARCHAR(200) NOT NULL,
	Cost DECIMAL(18,2) NOT NULL,
	CurrencyID BIGINT NOT NULL,
	MinQty INT NOT NULL,
	MaxQty INT NOT NULL,
	SafetyStockLevel INT NOT NULL,
	SupplierID BIGINT NOT NULL,
	Enabled NVARCHAR(1) NOT NULL Default 'Y',
	CreatedOn DATETIME NOT NULL,
	CreatedBy NVARCHAR(20) NOT NULL,
	ModifiedOn DATETIME NOT NULL,
	ModifiedBy NVARCHAR(20) NOT NULL)