//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESD.WITS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESD.WITS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Roles table
        ///
        ///CREATE TABLE Role(
        ///	ID BIGINT PRIMARY KEY,
        ///	Name NVARCHAR(200) NOT NULL,
        ///	Code NVARCHAR(100) NOT NULL,
        ///	Description NVARCHAR(100) NOT NULL,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;,
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	ModifiedBy NVARCHAR(20) NOT NULL).
        /// </summary>
        internal static string _01_CREATE_Table_Role {
            get {
                return ResourceManager.GetString("_01_CREATE_Table_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Users table
        ///
        ///CREATE TABLE Users (
        ///	ID BIGINT PRIMARY KEY,
        ///	Username NVARCHAR(20) NOT NULL,
        ///	Password NVARCHAR(32) NOT NULL,
        ///	Name NVARCHAR(200) NOT NULL,
        ///	Email NVARCHAR(100) NOT NULL,
        ///	RoleID BIGINT NOT NULL,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;,
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	ModifiedBy NVARCHAR(20) NOT NULL).
        /// </summary>
        internal static string _02_CREATE_Table_User {
            get {
                return ResourceManager.GetString("_02_CREATE_Table_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Currency table
        ///
        ///CREATE TABLE Currency(
        ///	ID BIGINT PRIMARY KEY,
        ///	Name NVARCHAR(200) NOT NULL,
        ///	Code NVARCHAR(100) NOT NULL,
        ///	Description NVARCHAR(100) NOT NULL,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;,
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	ModifiedBy NVARCHAR(20) NOT NULL).
        /// </summary>
        internal static string _03_CREATE_Table_Currency {
            get {
                return ResourceManager.GetString("_03_CREATE_Table_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Supplier table
        ///
        ///CREATE TABLE Supplier(
        ///	ID BIGINT PRIMARY KEY,
        ///	SupplierName NVARCHAR(500) NOT NULL,
        ///	ContactPerson NVARCHAR(200) NULL,
        ///	ContactTelNo NVARCHAR(100) NULL,	
        ///	ContactFaxNo NVARCHAR(100) NULL,	
        ///	Email NVARCHAR(100) NULL,	
        ///	Address NVARCHAR(500) NULL,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;,
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	ModifiedBy NVARCHAR(20) NOT NULL).
        /// </summary>
        internal static string _04_CREATE_Table_Supplier {
            get {
                return ResourceManager.GetString("_04_CREATE_Table_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Container table
        ///
        ///CREATE TABLE Container (
        ///	ID BIGINT PRIMARY KEY,
        ///	PartNumber NVARCHAR(200) NOT NULL,
        ///	Description NVARCHAR(135) NOT NULL,
        ///	MachineUsage NVARCHAR(200) NOT NULL,
        ///	Cost DECIMAL(18,2) NOT NULL,
        ///	CurrencyID BIGINT NOT NULL,
        ///	MinQty INT NOT NULL,
        ///	MaxQty INT NOT NULL,
        ///	SafetyStockLevel INT NOT NULL,
        ///	SupplierID BIGINT NOT NULL,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;,
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	Modifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _05_CREATE_Table_Container {
            get {
                return ResourceManager.GetString("_05_CREATE_Table_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Create Transactions table
        ///
        ///CREATE TABLE Transactions (
        ///	ID BIGINT PRIMARY KEY IDENTITY(1,1),
        ///	ContainerID BIGINT NOT NULL,
        ///	Quantity INT NOT NULL,
        ///	TxnType NVARCHAR(10) NOT NULL, --INDEX
        ///	IsOffline NVARCHAR(1) NOT NULL Default &apos;N&apos;,
        ///	IsSync NVARCHAR(1) NOT NULL Default &apos;N&apos;,
        ///	Enabled NVARCHAR(1) NOT NULL Default &apos;Y&apos;, --For Handheld device purposes
        ///	CreatedOn DATETIME NOT NULL,
        ///	CreatedBy NVARCHAR(20) NOT NULL,
        ///	ModifiedOn DATETIME NOT NULL,
        ///	ModifiedBy NVARCHAR(20) NOT NULL).
        /// </summary>
        internal static string _06_CREATE_Table_Transactions {
            get {
                return ResourceManager.GetString("_06_CREATE_Table_Transactions", resourceCulture);
            }
        }
    }
}
